### ISSUE TITLE
tag

### ISSUE THREAD

**Issue by eggplants** [eggplants/mice-behavior-tracking#3]
Releaseするarchiveファイルにタグのみを付与
```yml
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
```
